### ISSUE TITLE
`push': can't modify frozen Array (RuntimeError)

### ISSUE THREAD

**Issue by gen1321** [bricesanchez/spree-refinery-authentication#10]
http://stackoverflow.com/questions/31867940/push-cant-modify-frozen-array-runtimeerror

**Comment by bricesanchez** [comment]
Could you let me access to a source code, i can't reproduce your error ?

**Comment by gen1321** [comment]
https://github.com/gen1321/onlab  here. Thank you

**Comment by bricesanchez** [comment]
I've started a test app to show you, how i can install Spree and Refinery CMS together : 
https://github.com/bricesanchez/spree-refinerycms-test

Please read all commit comments and try to adapt to your use case
