### ISSUE TITLE
Please update the gem as they are not in sync with spree 3.4.4

### ISSUE THREAD

**Issue by amitbishtZT** [bricesanchez/spree-refinery-authentication#12]
jquery-ui-rails and deface gem versions are not updated thus unable to install this connector.

**Comment by bricesanchez** [comment]
Hi @amitbishtZT, 

Could you test this PR to see if it fixes your problem: #13

**Comment by Obi-TOB** [comment]
Works with Spree 3.6.1

**Comment by bricesanchez** [comment]
Thanks for your feedback @Obi-TOB, i merge this PR #13
