### ISSUE TITLE
Implicit Load Order dependency 

### ISSUE THREAD

**Issue by Obi-TOB** [bricesanchez/spree-refinery-authentication#14]
`app/decorators/controllers/spree/user_sessions_controller_decorator.rb` and
`app/decorators/controllers/spree/amin/user_sessions_controller_decorator.rb`

both require that
`app/decorators/controllers/action_controller_base_decorator.rb`
is loaded first.

This normally seems to happen, but not in all cases. However I have machines with the same project setup where the following exception occurs:
```
[...]
.rbenv/versions/2.5.1/gemsets/rails52/bundler/gems/spree-refinery-authentication-da83d4dbd36b/app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb:2:in 'block in <main>'
[...]
/.rbenv/versions/2.5.1/gemsets/rails52/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:701:in 'block (2 levels) in skip_callback': Before process_action callback :detect_spreefinery_single_sign_on! has not been defined (ArgumentError)
```

Not sure how the load order of the classes in a gem are defined in Rails, however an explicit reference
`require_relative '../../action_controller_base_decorator.rb'`
in
`app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb` resolves the issue.

I think this can be resolved better, however, if a PR helps let me know.

**Comment by bricesanchez** [comment]
Hi @Obi-TOB 

Feel free to open a PR if it can resolve bugs :)
