### ISSUE TITLE
cannot load such file -- refinery/core/authorisation_adapter (LoadError)

### ISSUE THREAD

**Issue by nuno84** [bricesanchez/spree-refinery-authentication#9]
Hello all,
When I run the server it keeps giving this error:
/home/nuno/.rvm/gems/ruby-2.1.6/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- refinery/core/authorisation_adapter (LoadError)

perhaps my refinery / spree gem version is wrong??
I hope you can give me a hand here...
thank you
this is my gemfile:

gem 'spree', '3.0.2.beta', github: 'spree/spree', branch: '3-0-stable'
branch: '3-0-stable'
gem 'spree_shared', github: 'spree-contrib/spree_shared', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
branch: '3-0-stable'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-0-stable'
gem 'spree_multi_currency', github: 'spree-contrib/spree_multi_currency', branch: '3-0-stable'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '3-0-stable'
# refinery CMS

gem 'refinerycms', github: 'refinery/refinerycms', branch: 'master'
gem 'refinerycms-authentication-devise', github: 'refinery/refinerycms-authentication-devise', branch: '3-0-stable'
gem 'quiet_assets', :group => :development
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']

**Comment by bricesanchez** [comment]
You can't have `spree_auth_devise` and `refinerycms-authentication-devise` gem on the same Gemfile

**Comment by bricesanchez** [comment]
With spree-refineryms-authentication, i use spree auth devise only

**Comment by nuno84** [comment]
I removed it.
It throws this error whrn I try to start the server:
/home/nuno/.rvm/gems/ruby-2.1.6/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- refinery/core/authorisation_manager (LoadError)

Can you tell me if you made it work with that spree version / refinery version / rails version?
I am scratching my head for a few days now!
Would you help me on this issue?
Perhaps can you tell me your gemfile so I can try to use the same gems?
Thanks

**Comment by bricesanchez** [comment]
This is my current working Gemfile: https://gist.github.com/bricesanchez/cfa2695368b5b31ade42

Hope it can help you!

**Comment by bricesanchez** [comment]
Found, you don't use the auth-for-real-yo-tmp branch of refinerycms

**Comment by nuno84** [comment]
Brice,
I will give a try with your gems, and let you know the results.
It seems that finally the bridge between refinery and spree has been created... awesome!!
Thank you so much for your help :)
Best,
Nuno

**Comment by nuno84** [comment]
Brice,
It it working great!
I am very thankfull to you... your work and help are priceless! People like you makes this community so powerfull and awesome!
Thank you so much :)
Best,
Nuno

**Comment by bricesanchez** [comment]
Thank you very much but @parndt has done the main work on this gem :)

**Comment by nuno84** [comment]
Brice,
I needed to add the @parndt version of wymeditor. The one you use won't let me add an image to a page... it loads a 404 on popup load

So I replaced the refinerycms-wymeditor gemfile line to this (maybe this can help someone who stumbles upon this subject): 
gem 'refinerycms-wymeditor',   github: 'parndt/refinerycms-wymeditor', branch: 'master'

It is working now.
Thank you for you help once again ;)
Best regards,
Nuno

**Comment by nuno84** [comment]
Brice,
Can you help me on this issue?
https://github.com/refinery/refinerycms/issues/3001
I am sorry to refer an issue on both sides but I guess it has something to do with that branch.
I can make it work on development but not on production.
Thank you so much
Best,
Nuno
